### ISSUE TITLE
AutoCraftingTable Duplication glitch

### ISSUE THREAD

**Issue by Mathemagician2** [DeadlyMC/QuickCarpet#90] opened 2021-06-03 14:59 UTC
You can trick the crafting gui into thinking there are items to be crafted so you can take the output without actually spending any resources. Similar to the bundle crafting dupe in 1.17 snapshots.

https://user-images.githubusercontent.com/85301261/120666640-5d808c00-c452-11eb-9cd5-cd10f0995f3b.mp4

**Comment by skyrising** [comment] 2021-06-12 21:20
Is this still happening in 3.1.0? If not this is probably a duplicate of #84 and already fixed.

**Comment by Mathemagician2** [comment] 2021-06-12 21:38
It seems to be fixed in 3.1.0.

**Closed** 2021-06-13 07:38 UTC
Labels: bug, question
